### ISSUE TITLE
Error loading binder

### ISSUE THREAD

**Issue by ScottCoffin** [Nano2PlastProject/TheFullMulti_RIVER#1]
![image](https://user-images.githubusercontent.com/56366258/147967712-8da22fd0-0c36-4d0e-80b4-fa00a4d920b4.png)

When launching Binder on Google Chrome, the following error message is reported in the log, and the application fails to complete launch.
"ERROR: Invalid requirement: 'Python implementation==CPython' (from line 9 of requiremements.txt)

**Comment by PradoDomercq** [comment]
Thanks for reporting. The requirements.txt has been fixed now and Binder should be launching correctly
