### ISSUE TITLE
Potential Error in the Codes of FullMulti_RiverModel_Notebook.ipynb and FullMulti_RiverModel_NotebookNew.ipynb

### ISSUE THREAD

**Issue by jskimuw** [Nano2PlastProject/TheFullMulti_RIVER#3]
Hi Prado,

In the module 'Define model run results file name,' this line is incorrect to my understanding.

LastDay = DayStart + timedelta(minutes=tmax)

Since tmax was defined as to total simulation period in second, this line should be

LastDay = DayStart + timedelta(seconds=tmax)

Please let me know what you think.

Thanks!

**Comment by PradoDomercq** [comment]
Thanks!

You are right! I have corrected this and it should show in the repository.

Thanks!
Best,
Prado
